src/frontend/App/context/BehandlingContext.tsx, src/frontend/App/hooks/useHentFormkravVilkår.ts, src/frontend/App/hooks/useHentVurderinger.ts, src/frontend/Komponenter/Behandling/Formkrav/EndreFormkravVurderinger.tsx, src/frontend/Komponenter/Behandling/Høyremeny/HistorikkInnslag.tsx, src/frontend/Komponenter/Behandling/Vurdering/InterntNotat.tsx, src/frontend/Komponenter/Behandling/Vurdering/Vurdering.tsx, src/frontend/Komponenter/Behandling/Vurdering/VurderingLesemodus.tsx, src/frontend/Komponenter/Behandling/Vurdering/vurderingValg.ts
Løser tilbakemeldinger etter brukertest:
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10266)
- Refaktorert i forbindelse med henting av vurdering
- Refakturert ut InterntNotat i egen komponent
- Lagt til et felt på vurdering, begrunnelseOmgjøring. Dette feltet er påkrevd ved omgjøring av vedtak.
- Tekstlige endringer etter tilbakemeldinger fra bruker
Backend:
* https://github.com/navikt/familie-klage/pull/155
Vurderingsfanen ved omgjøring ser nå slik ut:
=> Tilbakemeldinger brukertest utbedringer

src/frontend/Komponenter/Behandling/Formkrav/EndreFormkravVurderinger.tsx, src/frontend/Komponenter/Behandling/Formkrav/Formkrav.tsx, src/frontend/Komponenter/Behandling/Formkrav/VedtakSelect.tsx, src/frontend/Komponenter/Behandling/Formkrav/VisEllerEndreFormkravVurderinger.tsx, src/frontend/Komponenter/Behandling/Formkrav/VisFormkravVurderinger.tsx, src/frontend/Komponenter/Behandling/Formkrav/utils.ts, src/frontend/Komponenter/Behandling/Høyremeny/Historikk.tsx, src/frontend/Komponenter/Behandling/Høyremeny/HistorikkInnslag.tsx, src/frontend/Komponenter/Behandling/utils.ts
- Dette då vi kanskje ikke har en vurdering å sjekke resultatet fra hvis man endret formkravet eller henlagt
Ytterligare forbedring fra tidligere PR's
Det kan bli vist feil resultat på formkrav/vurdering hvis man eks henlagt eller endret formkravet og då ikke har en vurdering noe lengre. 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10449
=> Skal kun vise utfall for hendelsen ferdigstilt behandling i historikken

src/frontend/App/typer/kanOppretteRevurdering.ts, src/frontend/App/typer/ressurs.ts, src/frontend/Komponenter/Behandling/Brev/Brev.tsx, src/frontend/Komponenter/Behandling/Brev/OmgjørVedtak.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10275
Det er ønskelig å vise en info-tekst når man klikker på ferdigstill som sier om en ny behandling kan opprettes eller ikke (se skisser)
* https://github.com/navikt/familie-klage/pull/214
* https://github.com/navikt/familie-ef-sak/pull/1963
=> Opprett revurdering automatisk info

src/frontend/Komponenter/Behandling/Brev/OmgjørVedtak.tsx, src/frontend/Komponenter/Behandling/Resultat/Tidslinje.tsx
Flytter opp label over detail i resultat
Siste fiks på denne?  https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10275
=> Fikser tekster for automatisk opprettelse av revurdering

src/frontend/Komponenter/Behandling/Fanemeny/Fanemeny.tsx, src/frontend/Komponenter/Behandling/Henleggelse/HenleggModal.tsx
Laster behandling og behandlingshistorikk ved henleggelse for att resultatet skal vises riktig på resultatsiden, og historikken
https://nav-it.slack.com/archives/G012YEK9YQ1/p1671109217274759
=> Låser brevfanen for henlagte behandlinger

src/frontend/Komponenter/Behandling/Brevmottakere/BrevmottakereModal.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/SøkPerson.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/SøkWrapper.tsx
Hvorfor ? 
PDL klienten i backend bruker stønadstype for å utlede tema og behandlingsnummer, og derfor må behandlingId sendes til backend. 
Se : https://github.com/navikt/familie-klage/pull/306
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12402
=> Trenger behandlingId i SøkPerson komponent for å søke etter person

src/frontend/App/typer/fagsak.ts, src/frontend/Komponenter/Behandling/Resultat/AnkeVisning.tsx, src/frontend/Komponenter/Behandling/Resultat/FeilregistrertVisning.tsx, src/frontend/Komponenter/Behandling/Resultat/Resultat.tsx, src/frontend/Komponenter/Behandling/Resultat/utils.ts
Når en behandling er feilregistrert i kabal blir denne ferdigstilt hos oss. Vi må derfor vise begrunnelse og tidspunkt for feilregistrering.
=> Skal vise info om feilregistrert behandling

build_n_deploy/naiserator/dev.yaml, build_n_deploy/naiserator/prod.yaml
Anbefaling fra NAIS om at CPU throttle fjernes fra pod, men beholdes for requests: https://nav-it.slack.com/archives/C01DE3M9YBV/p1680172494569329
Artikkelen som det refereres til i meldingen fra NAIS beskriver hvorfor:
https://home.robusta.dev/blog/stop-using-cpu-limits
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-12306)
=> Fjerner CPU-limit

build_n_deploy/naiserator/dev.yaml, build_n_deploy/naiserator/prod.yaml
Deploy vil slutte å fungere etter 18. desember uten denne endringen
=> skal ha gyldig nais template

package.json, src/frontend/Komponenter/Behandling/Høyremeny/Dokumenter.tsx, src/frontend/Komponenter/Behandling/Høyremeny/Dokumentliste.tsx, src/frontend/Komponenter/Behandling/Høyremeny/LogiskeVedlegg.tsx, yarn.lock
* Fjernet avhengigheten familie-dokumentliste. 
* Flyttet kode fra familie-felles-frontend. 
* Refaktorert Dokumentliste til å bruke tag med bokstaver i stedet for piler.
Bildet viser nytt design:
=> Refaktorert dokumentliste

src/frontend/App/context/toggles.ts, src/frontend/Felles/Visittkort/HenleggKnapp.tsx, src/frontend/Felles/Visittkort/SettPåVentKnapp.tsx, src/frontend/Felles/Visittkort/Visittkort.tsx
Klage ønsker å gjøre det mulig å sette klagebehandling på vent. Før vi introduserer innholdet, kan det være lurt å feature toggle dette. Denne PRen gjemmer en sett på vent knapp bak feature toggle. Denne funksjonaliteten depender på denne [PRen](https://github.com/navikt/familie-klage-frontend/pull/862) i `ef-klage` som introduserer selve togglene.
=> Gjemt SettPåVentKnapp bak feature toggle.

src/frontend/Komponenter/Behandling/Brev/Brev.tsx, src/frontend/Komponenter/Behandling/Brev/BrevFane.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/BrevmottakerContainer.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/panel/BrevmottakerPanel.tsx
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23444
Kobler sammen koden for brevmottakere laget i en tidligere [PR](https://github.com/navikt/familie-klage-frontend/pull/867) sammen med den eksisterende koden.
Har kjørt løsningen lokalt og det ser ut til å fungere fint.
=> NAV-23444: Kobler sammen baks sin BrevmottakerContainer til Brev

src/frontend/App/typer/toast.ts, src/frontend/Felles/Toast/Toast.tsx, src/frontend/Felles/Visningskomponenter/Alerts.tsx, src/frontend/Komponenter/Behandling/SettPåVent/SettPåVent.tsx, src/frontend/Komponenter/Behandling/Typer/IOppgave.ts
Denne PRen har som hensikt å addresse et funn fra testing, der den som tar behandlingen av vent blir deligert som ansvarlig saksbehandler. Vi sender også med oppgave versjon.
Det vises også nå en toast får når behandling er satt/tatt av vent. 
Denne [PRen](https://github.com/navikt/familie-klage-frontend/compare/main...feature/vent-oppgave-versjon) depender på denne [PRen](https://github.com/navikt/familie-klage/pull/571) (back-end).
Funn fra test og oppgave kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22627).
=> Feature - deliger oppgave til saksbehandler som tar klagebehandling av vent

src/frontend/Komponenter/Behandling/Formkrav/validerFormkravUtils.ts
En liten bug der feil visningsmodus blir satt når bruker trykker lagre på "ikke klaget på vedtak" formkravet. Selve lagringen skjer, men visningsmodus ble feil. Denne endringen fikser dette. 
Oppgaven og beskrivelse kan du finne på Favro → [her](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24140).
Har testet ved å prøve de forskjellige valgene. Prøvd å ta for meg de forskjellige statene som kan påvirke dette, men virker som det ikke er noen tilfeller der dette blir feil.
=> Bugfiks - visningsmodus er nå satt til visning etter man har lagret formkrav for "har ikke klaget på vedtak"

src/frontend/Komponenter/Behandling/Brev/Brev.tsx
En kodesnutt som ble lagt til tidligere fjernet lesevisning av pdf ved opprettholdelse. Denne PRen fikser dette.
=> bugfix: skal kunne vise pdf i lesevisning

src/frontend/App/context/toggles.ts, src/frontend/Komponenter/Behandling/Brev/Brev.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/BrevmottakerContainer.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/panel/BrevmottakerPanel.tsx
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24253
Viser brevmottaker komponenter for BAKS når fagsystemet er KS eller BA, og toggle(s) er skrudd på.
En toggle for å vise selve brevmottaker panelet til BAKS.
En annen toggle for å vise knappen for å vise modalen for å legge til manuelle brevmottakere. 
Har kjørt løsningen opp lokalt og det ser ut til å fungere fint.
=> NAV-24253: Viser baks brevmottaker komponenter, bak en toggle

src/frontend/Komponenter/Behandling/Brevmottakere/baks/panel/BrevmottakerPanel.tsx
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24253
Legger til en `<Alert />` som forklarer hvorfor det ikke er mulig å legge til manuelle brevmottakere. 
Har kjørt opp løsningen lokalt og ser ut til å fungere fint.
Screenshot:
=> NAV-24253: Legger til en alert for å forklare hvorfor manuelle brevmottaker ikke er mulig å legge til

src/frontend/Komponenter/Behandling/Vurdering/InnstillingTilNavKlageinstans/InnstillingTilNavKlageinstans.tsx, src/frontend/Komponenter/Behandling/Vurdering/InnstillingTilNavKlageinstans/InnstillingTilNavKlageinstansAvsnitt.tsx, src/frontend/Komponenter/Behandling/Vurdering/InnstillingTilNavKlageinstans/LesMerOmInnstilling.tsx, src/frontend/Komponenter/Behandling/Vurdering/Vurdering.tsx, src/frontend/Komponenter/Behandling/Vurdering/vurderingValg.ts
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24683)
I klager for barnetrygd og kontantstøtte må saksbehandlerne kunne fylle ut fem felter i innstilling til Nav Klageinstans, i stedet for ett.
- Legger til de nye feltene som optional i `IVurdering`
- Viser fem `Accordion` for de nye feltene dersom fagsystem er BA eller KS
- Tilpasser valideringen til fagsystem
=> Utvider innstilling til Nav klageinstans med flere felter

src/frontend/Komponenter/Behandling/Vurdering/InnstillingTilNavKlageinstans/InnstillingTilNavKlageinstans.tsx, src/frontend/Komponenter/Behandling/Vurdering/InnstillingTilNavKlageinstans/InnstillingTilNavKlageinstansAvsnitt.tsx
Vi ønsker at første accordion i Innstilling til Nav Klageinstans for behandlinger for BA og KS skal være default åpen
=> Sett første accordion i Innstilling til Nav Klageinstans som default åpen

src/frontend/Komponenter/Behandling/Brev/Brev.tsx, src/frontend/Komponenter/Behandling/Brev/BrevFaneUtenBrev.tsx, src/frontend/Komponenter/Behandling/Brev/OmgjørVedtak.tsx, src/frontend/Komponenter/Behandling/Brev/useFerdigstillBehandling.ts
Favro: [NAV-24779](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24779)
Flytter duplisert "ferdigstillings"-kode inn i eget `hook` og tar i bruk `hooket` i henholdsvis `Brev`, `BrevFaneUtenBrev` og `OmgjørVedtak`.
[Tilhørende backend PR.](https://github.com/navikt/familie-klage/pull/629)
=> NAV-24779: Justere kode relatert til ferdigstilling av behandling

src/frontend/Komponenter/Behandling/Formkrav/EndreFormkravVurderinger.tsx, src/frontend/Komponenter/Behandling/Formkrav/VisFormkravVurderinger.tsx, src/frontend/Komponenter/Behandling/Formkrav/utils.ts
Favro: [NAV-24774](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24774)
Viser felt for intern begrunnelse samt fritekstfelt for begrunnelse til brev dersom alle formkrav er oppfylt med unntak av klagefrist-formkravet og et av unntakene til formkravet er oppfylt. I dette tilfellet vises også en annen hjelpetekst tilknyttet fritekstfeltet.
Justerer også validering av fritekst-feltene.
[Tilknyttet backend PR](https://github.com/navikt/familie-klage/pull/627).
Screenshots:
=> NAV-24774: Intern begrunnelse og fritekstfelt dersom unntak om klagefrist er oppfylt

src/frontend/Komponenter/Behandling/Formkrav/VedtakSelect.tsx
Meldt i teams hvor det er problemer med å lagre formkrav.
Det viser seg at bug'n gjelder for klage på tilbakekreving. Tidligere if-sjekk antok at alle uuid's var en intern klagebehandling, men tilbakekreving har uuid som ekstern id, og det ble derfor feil. Retter dette ved å markere intern-id'er mer spesifikt. Dette er en midlertidig løsning for saksbehandlere, men dette burde skrives om til at value i kombobox inneholder mer typet informasjon.
=> Bugfix: Markerer internId med en prefix for å skille på om det er en intern klagebehandling eller ekstern behandling

src/frontend/Komponenter/Behandling/Brev/Brev.tsx
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24862
Toggle er skrudd på i prod og trengs ikke lengre. 
Relatert backend PR: https://github.com/navikt/familie-klage/pull/628
=> NAV-24862: Fjerne toggle for å vise brevmottaker BAKS variant

src/frontend/App/context/toggles.ts
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24862
Toggelen er allerede fjernet, men glemte å fjerne innslaget fra `toggles.ts` filen.
=> NAV-24862: Fjerner "visbrevmottakerBaks" fra toggles.ts da det ble glemt når toggelen ble fjernet.

src/frontend/Komponenter/Behandling/Vurdering/VurderingRedigeringsmodusBaks/InnstillingTilNavKlageinstans.tsx, src/frontend/Komponenter/Behandling/Vurdering/VurderingRedigeringsmodusBaks/InnstillingTilNavKlageinstansAvsnitt.tsx, src/frontend/Komponenter/Behandling/Vurdering/VurderingRedigeringsmodusBaks/Nedtrekksliste.tsx, src/frontend/Komponenter/Behandling/Vurdering/VurderingRedigeringsmodusBaks/Tekstfelt.tsx, src/frontend/Komponenter/Behandling/Vurdering/VurderingRedigeringsmodusBaks/VurderingRedigeringsmodus.tsx, src/frontend/Komponenter/Behandling/Vurdering/VurderingRedigeringsmodusBaks/felttyper.ts, src/frontend/Komponenter/Behandling/Vurdering/vurderingValg.ts
Fikser en bug som skyldes at tekstfeltet settes til `undefined` når det er tom string, som gjør at react-hook-form setter feltet til default. Endrer slik at det heller settes til `null`
=> Ikke sett tekstfelt til null i stedet for undefined når det er tom streng

.github/dependabot.yml, .github/workflows/build_dev.yaml, .github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml
💰 Hva forsøker du å løse i denne PR'en
Ta i bruk ratchet og dependabot for github actions. Som vil gi oss up-to-date versjoner av workflows vi bruker. Vi lærte i tech-prat at å lene seg på versjonnummer alene utgir en sikkerhetsrisiko.
=> Pin actions med ratchet

src/frontend/Komponenter/Behandling/Brev/Brev.tsx
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25013)
I #920 ble det innført en bug som endret logikken for visning, som gjorde at brevmottakere ble hentet før brevet var generert.
Legger til parentes rundt visningen, slik at ingen av komponentene blir vist før brevmottakere er lastet inn.
=> Fiks bug i henting av brevmottakere

src/frontend/Komponenter/Behandling/Brevmottakere/ef/BrevMottakere.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/ef/BrevmottakereModal.tsx
Tar i bruk nytt endepunkt introdusert her: https://github.com/navikt/familie-klage/pull/580/files#diff-0605af2946628192a02eec366e875835c1e4979bdf3cb4a75b47ec67f867b74dR41-R51
Hvis man går over til den endepunktet kan man fjerne brevmottaker koden i PRen her: https://github.com/navikt/familie-klage/pull/585
Har kjørt og opp løsningen lokalt og ser ut til å fungere fint ut i fra det jeg ser.
=> Går over til nytt endepunkt for brevmottakere for team EF

src/frontend/Felles/Landvelger/EøsLandvelger.tsx, src/frontend/Felles/Landvelger/landkode.ts, src/frontend/Komponenter/Behandling/Brevmottakere/baks/BrevmottakerContainer.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/BrevmottakerForm.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/Adresselinje1Felt.test.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/Adresselinje1Felt.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/Adresselinje2Felt.test.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/Adresselinje2Felt.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/AdresselinjeFelt.test.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/AdresselinjeFelt.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/LandFelt.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/MottakerFelt.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/NavnFelt.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/PostnummerFelt.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/PoststedFelt.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/felttyper.ts, src/frontend/Komponenter/Behandling/Brevmottakere/brevmottaker.ts, src/frontend/Komponenter/Behandling/Brevmottakere/mottakerRolle.ts, src/frontend/Komponenter/Behandling/Brevmottakere/nyBrevmottaker.test.ts
Favro: [NAV-25011](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25011)
Refaktorer eksisterende brevmottaker form/felter litt da det skal gjenbrukes en del logikk i "henlegg behandling" modalen.
Har kjørt opp løsningen og ser ut til å fungere bra. 
Det enkleste er kanskje bare å sjekke ut branchen selv å gå gjennom kode der, ble en litt uoversiktlig PR.
=> Nav 25011 refaktorer brevmottaker felter

src/frontend/Komponenter/Behandling/Vurdering/InterntNotat.tsx, src/frontend/Komponenter/Behandling/Vurdering/VurderingRedigeringsmodus.tsx
Setter vurdering endret når man oppdaterer tekst i internnotat, så man får lagret om det er den eneste endringen man gjør.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25242)
=> Setter vurdering endret når man oppdaterer tekst i internnotat

src/frontend/Komponenter/Behandling/Henleggelse/HenleggBehandlingModalInnhold.tsx
Favro: [NAV-25011](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25011)
Gjør "henlegg" knappen inaktiv når man har åpnet brevmottaker-skjemaet for å forhindre noen å fylle ut skjemaet for å så trykke "henlegg" før de trykker "legg til brevmottaker". La til en melding over skjemaet som forklarer hvorfor "henlegg" knappen er inaktiv. 
Når brevmottaker-skjemaet er åpent:
Når brevmottaker-skjemaet er lukket:
=> NAV-25011: Setter "henlegg" knappen til å være inaktiv når man åpner brevmottaker-skjemaet

src/frontend/Komponenter/Behandling/Resultat/utils.ts
Oppstått tilfelle hvor det er registrert klageresultat KLAGEBEHANDLING_AVSLUTTET og BEHANDLING_FEILREGISTRERT i samme klage behandling. Som koden var før ville resultatet behandling feilregistrert ta prioritet over behandling avsluttet som fører til forvirring. Flytter dermed sjekken for feilregistrert etter avsluttet.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-25326)
=> Flyttet sjekk for klagebehandling avsluttet før sjekk for behandlingfeilregistert

src/frontend/Felles/HeaderMedSøk/HeaderMedSøk.tsx
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25659
Man sendte ikke med enhet når man oppretter Header komponenten som førte til at det sto Ukjent Enhet.
Før:
Etter:
=> Legg til manglende enhet i header

package.json, yarn.lock
Ser ut til å være typer til en pakke vi ikke bruker lengre, og som har vært deprekert siden 2020. 
Den blokkerer patching av sårbarhet pga. peer-dependency.
=> Fjern @types/request-promise

src/frontend/Felles/Landvelger/EøsLandvelger.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/BrevmottakerModalBody.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/BrevmottakerForm.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/LandFelt.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/felt/MottakerFelt.tsx, src/frontend/Komponenter/Behandling/Brevmottakere/mottakerRolle.ts, src/frontend/Komponenter/Behandling/Henleggelse/hooks/useBrevmottakerForm.ts
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-26390
Oppdaget at det var oppstått flere bugs i brevmottaker skjema når man legger til brevmottakere enten på brev fanen eller når man henlegger en behandling. Gjør også noen opprydninger.
- Går over til `error.root` fra en custom `onSubmitServerError` error type. 
- Fjerner "-- Velg land --" fra landvelger da den alltid skal være preutfylt med "Norge" og land er alltid påkrevd.
- Landvelger kan ikke lengre "unselecte" et valg. Hvis man velger det samme landet blir det bare værende som valgt.
- Tilbakestiller felter manuelt i stedet for å bruke  `shouldUnregister`. `shouldUnregister` ga rare feil. 
- Filtrer bort den nye mottaker rollen `MOTTAKER`.
=> NAV-26390: Rydder opp og fikser noen bugs i brevmottaker skjema
