navikt/familie-klage-frontend

- src/frontend/Komponenter/test/TestSide.tsx
> Opprett dummybehandling

- src/frontend/App/typer/fagsak.ts
.. og fjerner dem vi har fjernet i backend.
> Legger til steg "OVERFØRING_TIL_KABAL"

- src/frontend/Komponenter/Behandling/Brev/Brev.tsx
- src/frontend/Komponenter/Behandling/Brev/BrevModal.tsx
Navigerer kun til resultatsiden hvis ferdigstilling går bra
Avhenger av https://github.com/navikt/familie-klage/pull/46
> Vil vise feil dersom ferdigstilling feiler.

- src/frontend/App/typer/fagsak.ts
- src/frontend/Komponenter/Behandling/Resultat/TidslinjeContainer.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9672
* https://github.com/navikt/familie-klage/pull/48
> Skal vise at vi har sendt og venter på svar fra kabal

- src/frontend/Komponenter/Behandling/Formkrav/typer.ts
> Fjerner fagsakId fra formkrav

- src/frontend/App/typer/fagsak.ts
Fikser at resultatet blir stående blankt ved henleggelse
> Henlagt skal være et mulig behandlingsresultat.

- src/frontend/App/typer/personopplysninger.ts
- src/frontend/Felles/Varsel/AdressebeskyttelseVarsel.tsx
- src/frontend/Felles/Varsel/Etikett.tsx
- src/frontend/Felles/Varsel/PersonStatusVarsel.tsx
- src/frontend/Felles/Visittkort/Visittkort.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9965
Avhengig av:
* https://github.com/navikt/familie-klage/pull/106
> Etiketter i header koblet til pdl-data

- src/frontend/Komponenter/Behandling/Fanemeny/Fanemeny.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9789
> Deaktiver brevfane for medhold

- src/frontend/Komponenter/Behandling/Brev/FritekstBrev.tsx
Midlertidig fiks før brukertest etter bestilling fra Lars.
> Skal ikke preutfylle overskrifter i brev

- src/frontend/App/api/axios.ts
- src/frontend/App/hooks/felles/useEffectNotInitialRender.ts
- src/frontend/App/typer/fagsak.ts
- src/frontend/Komponenter/Behandling/Formkrav/EndreFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/Formkrav.tsx
- src/frontend/Komponenter/Behandling/Formkrav/KlageInfo.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VisEllerEndreFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VisFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/typer.ts
- src/frontend/Komponenter/Behandling/Formkrav/utils.ts
Skal hente ut valgbare vedtak fra fagsystemet samt kunne sette påklaget vedtak i formkrav-siden
> Skal kunne velge påklaget vedtak

- src/frontend/Felles/Input/EnsligTextArea.tsx
- src/frontend/Komponenter/Behandling/Vurdering/Vurdering.tsx
- src/frontend/Komponenter/Behandling/Vurdering/vurderingValg.ts
Må merges etter https://github.com/navikt/familie-klage/pull/126
> Skal kunne legge til internt notat ved vurdering av klage

- src/frontend/Komponenter/Behandling/Brev/Brev.tsx
- src/frontend/Komponenter/Behandling/Fanemeny/Fanemeny.tsx
- src/frontend/Komponenter/Behandling/Vurdering/Vurdering.tsx
> Skal gå til brevfane for ferdigstilling ved omgjøring av vedtak

- src/frontend/Komponenter/Behandling/Brev/Brev.tsx
- src/frontend/Komponenter/Behandling/Brev/PdfVisning.tsx
- src/frontend/Komponenter/Behandling/Brevmottakere/BrevMottakere.tsx
Ikke pixel-perfect, men Lars ønsket å ha den ved siden av. Også lagt til at brevpdf faller ned under venstrekolonnen ved smal skjerm
> Skal vise brevmottakere ved siden av brevet

- src/frontend/Komponenter/Behandling/Brev/Brev.tsx
- src/frontend/Komponenter/Behandling/Formkrav/EndreFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VisEllerEndreFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VisFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/typer.ts
- src/frontend/Komponenter/Behandling/Formkrav/validerFormkravUtils.ts
- src/frontend/Komponenter/Behandling/Resultat/Resultat.tsx
- src/frontend/Komponenter/Behandling/Resultat/Tidslinje.tsx
Løser delvis [dette kortet](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10172)
Avhengig av backend:
* https://github.com/navikt/familie-klage/pull/145
Fritekstfelt som skal inkluderes i brevet:
> Fritekst brevfelt formkrav

- src/frontend/Komponenter/Behandling/Vurdering/Vedtak.tsx
- src/frontend/Komponenter/Behandling/Vurdering/Vurdering.tsx
- src/frontend/Komponenter/Behandling/Vurdering/VurderingLesemodus.tsx
- src/frontend/Komponenter/Behandling/Vurdering/vurderingValg.ts
- src/frontend/Komponenter/Behandling/Vurdering/Årsak.tsx
Avhengig av: 
* https://github.com/navikt/familie-klage/pull/157
> vurdering sin årsak skal skrives med å: arsak -> årsak

- src/frontend/Komponenter/Behandling/Vurdering/VurderingLesemodus.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10297
> Linjeskift for fritekst

- src/frontend/Komponenter/Behandling/Formkrav/EndreFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VisFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/typer.ts
- src/frontend/Komponenter/Behandling/Formkrav/utils.ts
Vil legge til hjelpetekster på formkrav. 
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10464
> Formkrav hjelpetekst

- src/frontend/Komponenter/Behandling/Resultat/Tidslinje.tsx
- skjer når man først oppfylt formkrav, lagrer vurdering, og sen avviser formkraven
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10449
> Skal ikke vise vurdering i resultat når formkraven er avvist.

- src/frontend/App/hooks/useHentFagsystemVedtak.ts
- src/frontend/App/hooks/useHentFormkravVilkår.ts
- src/frontend/App/typer/fagsak.ts
- src/frontend/App/typer/fagsystemVedtak.ts
- src/frontend/App/utils/utils.ts
- src/frontend/Komponenter/Behandling/Formkrav/Formkrav.tsx
- src/frontend/Komponenter/Behandling/Formkrav/typer.ts
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10461
* https://github.com/navikt/familie-klage/pull/198
> Skal ikke hente fagsystem vedtak ved låst behandling

- src/frontend/Komponenter/Behandling/Vurdering/vurderingValg.ts
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10570
> skal fjerne køet behandling fra årsak til omgjøring

- src/frontend/App/context/BehandlingContext.tsx
- src/frontend/Komponenter/Behandling/Resultat/Tidslinje.tsx
Litt ekstra håndtering av resultatsiden koblet til
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10449
> Viser kun opprettet- og ferdigstilt-node for henlagte behandlinger

- src/frontend/App/typer/fagsak.ts
- src/frontend/Komponenter/Behandling/Formkrav/VedtakSelect.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VisFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/typer.ts
- src/frontend/Komponenter/Behandling/Formkrav/utils.ts
- src/frontend/Komponenter/Behandling/Formkrav/validerFormkravUtils.ts
Usikker på om dette er beste måten å løse innsending/uthenting på. Tar gjerne innspill på andre forslag.
[Løser denne](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10607)
> Skal kunne velge påklaget vedtak fra infotrygd

- src/frontend/App/typer/fagsak.ts
- src/frontend/App/utils/utils.ts
- src/frontend/Komponenter/Behandling/Brev/Brev.tsx
- src/frontend/Komponenter/Behandling/Resultat/Tidslinje.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10275
https://github.com/navikt/familie-klage/pull/210
> Skal vise lenge til automatisk opprettet revurdering ved medhold

- src/frontend/Komponenter/Behandling/BehandlingContainer.tsx
Løser https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10597
> Faner i klage skal hete "Klagebehandling"

- src/frontend/Komponenter/Behandling/Formkrav/EndreFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VisFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/utils.ts
[Løser dette kortet](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10241)
Backend:
* https://github.com/navikt/familie-klage/pull/216
> Ikke påklaget vedtak avvisning

- src/frontend/App/typer/fagsak.ts
- src/frontend/Komponenter/Behandling/Formkrav/VedtakSelect.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VisFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/typer.ts
- src/frontend/Komponenter/Behandling/Formkrav/utils.ts
- src/frontend/Komponenter/Behandling/Formkrav/validerFormkravUtils.ts
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10666
> Skal kunne velge utestengelse som påklaget vedtak

- src/frontend/App/utils/dato.ts
- src/frontend/Komponenter/Behandling/Formkrav/VedtakSelect.tsx
- src/frontend/Komponenter/Behandling/Formkrav/validerFormkravUtils.ts
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10778
> Skal ikke kunne velge vedtaksdato frem i tiden

- src/frontend/App/typer/fagsak.ts
- src/frontend/Komponenter/Behandling/Formkrav/VedtakSelect.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VisFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/utils.ts
- src/frontend/Komponenter/Behandling/Formkrav/validerFormkravUtils.ts
Oppgave [Tea-10933](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10933)
Hører sammen med [PR 247](https://github.com/navikt/familie-klage/pull/247) i familie-klage
> Legge til ordinært stønadsvedtak i infotrygd som PåklagetVedtaksType

- src/frontend/Komponenter/Behandling/Vurdering/hjemmel.ts
https://github.com/navikt/familie-klage/pull/252
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-11006
Litt lange tekster, Mirja ser kanskje på mulighet for å korte de ned
> Legger inn hjemmel for 22-12 og 22-13

- src/frontend/App/context/toggles.ts
- src/frontend/Komponenter/Behandling/Brev/OmgjørVedtak.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VedtakSelect.tsx
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10635
@charliemidtlyng  jeg fjernet din og :)
> Fjerner toggles

- .github/workflows/build_dev.yaml
- .github/workflows/build_n_deploy_dev.yaml
- .github/workflows/build_n_deploy_prod.yaml
- Dockerfile
Tester i preprod før merge.
Har oppgradert ef-sak-frontend uten problemer så burde gå fint her også https://github.com/navikt/familie-ef-sak-frontend/pull/2116
> Bruk node 18

- LICENSE
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-9736
> Legger til MIT-lisens

- src/backend/config.ts
- src/backend/konfigurerApp.ts
**Hvorfor?**
For å kunne teste med data som ikke kan mockes.
> Skal kunne kjøre klage lokalt mot preprod

- src/frontend/Komponenter/Behandling/Vurdering/Vedtak.tsx
Ønsker at teksten som har blitt fylt inn under 'Innstilling til NAV Klageinstans' blir mellomlagret dersom man bytter til et annet vedtak og tilbake.
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-15810
> Mellomlagre teksten 'Innstilling til NAV Klageinstans'

- README.md
- src/frontend/Felles/Input/EnsligTextArea.tsx
- src/frontend/Komponenter/Behandling/Vurdering/InterntNotat.tsx
- src/frontend/Komponenter/Behandling/Vurdering/Vurdering.tsx
Ønsker å fjerne flest mulig felleskomponenter: [Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-18273)
> sletter FamilieTextArea og erstatter denne med TextArea fra Aksel

- README.md
- hent-og-lagre-miljøvariabler.sh
Gjør det enklere å sette opp lokal kjøring. Testet at det virket selv lokalt, men gjerne ta en sjekk på om det virker hos deg :)
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-20862)
> Automatisk oppsett for lokal kjøring

- src/frontend/App/typer/fagsak.ts
- src/frontend/Komponenter/Behandling/BehandlingContainer.tsx
- src/frontend/Komponenter/Behandling/BehandlingRoutes.tsx
- src/frontend/Komponenter/Behandling/Brev/Brev.tsx
- src/frontend/Komponenter/Behandling/Brev/BrevFane.tsx
- src/frontend/Komponenter/Behandling/Brev/BrevFaneUtenBrev.tsx
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22595)
Denne PRen gjør slik at det ikke opprettes noe brev ved ferdigstillelse av klage med årsak `henvendelse fra kabal`
> Klage uten brev

- src/frontend/App/typer/fagsak.ts
- src/frontend/Felles/Varsel/Etikett.tsx
- src/frontend/Felles/Visittkort/Visittkort.tsx
- src/frontend/Komponenter/Behandling/Brev/BrevFaneUtenBrev.tsx
Oppdaterer infotekst ut mot bruker og legger til en Tag:
> Oppdatere infotekst

- build_n_deploy/naiserator/dev.yaml
- build_n_deploy/naiserator/prod.yaml
- package.json
- src/frontend/App.tsx
- src/frontend/App/utils/grafanaFaro.ts
- yarn.lock
Skrur på NAIS auto-instrumentation, samt bruker Grafana Faro for å samle inn telemetri. I vårt tilfelle: metrikker og tracing-data.
https://docs.nais.io/observability/how-to/auto-instrumentation/
https://docs.nais.io/observability/frontend/
> Legg til auto-instrumentation + grafana faro

- .github/workflows/build_n_deploy_dev.yaml
- .github/workflows/build_n_deploy_prod.yaml
- package.json
- src/backend/server-felles.ts
- src/backend/server-lokal.ts
- src/backend/server.ts
For å ta ned sårbarheter ønsker vi ikke å inkludere alt av devdependencies i docker-bygget vårt (webpack, babel osv)
> Skal ikke ha med devdependencies i docker-bygget

- src/backend/config.ts
- src/frontend/App/typer/eksternlenker.ts
- src/frontend/App/utils/utils.ts
- src/frontend/Felles/Visittkort/Visittkort.tsx
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23195)
Lagt til lenker til saksoversikt, behandling og tilbakekreving.
> Gå tilbake fra klage til ef sak

- src/frontend/Komponenter/Behandling/BehandlingRoutes.tsx
- src/frontend/Komponenter/Behandling/Formkrav/EndreFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/Formkrav.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VedtakSelect.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VisEllerEndreFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Vurdering/Vurdering.tsx
Tre ting fikses: 
1. Fjerner "Utestengelse" som valgmulighet hvis det er BA/KS https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23458
2. Lage mer spesifikke eksempler for BA og KS https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23461
3. Rydder opp i hvilke hjemler man kan velge for BA og KS https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23463
> Justeringer for BAKS

- src/frontend/Komponenter/Behandling/Vurdering/hjemmel.ts
Fjern utland EØS 5 og 6, samt rename EØS-avtalen til EØS-regelverket
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23463
Skulle ha vært med her: https://github.com/navikt/familie-klage-frontend/pull/853
> Justeringer av hjemler for BAKS

- src/frontend/Komponenter/Behandling/Vurdering/hjemmel.ts
Favro: [NAV-23545](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23545)
Avhengig av at backend-endringer rulles ut først: https://github.com/navikt/familie-klage/pull/553
> Legger til manglende hjemler for barnetrygd og kontantstøtte

- src/frontend/Komponenter/Behandling/Brev/Brev.tsx
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23920
Gjemmer BAKS dialogen igjen da det var litt tidlig å vise den
> NAV-23920: Gjemmer baks brev

- src/frontend/Komponenter/Behandling/Vurdering/hjemmel.ts
Favro: [NAV-23545](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23545)
> Legger til prefix på hjemler for barnetrygdloven, kontantstøtteloven, forvaltningsloven, og folketrygdloven

- src/backend/config.ts
Team Tilbake skal ta over tilbakekrevingsløsningen. Den eksisterende løsningen kjører nå i teamfamilie nais teamet, og for å ta ordentlig eierskap til løsningen og gjøre det til en NAV fellestjeneste ønsker vi å flytte det til et NAIS team som er mer generelt.
> Ta i bruk tilbakekreving som er flyttet til nytt nais team i preprod

- build_n_deploy/naiserator/dev.yaml
- build_n_deploy/naiserator/prod.yaml
- src/backend/config.ts
Hvorfor er denne endringen nødvendig? ✨
Redis på Aiven skal legges ned - må bytte til Valkey.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24047)
> SKal ta ibruk VALKEY istedenfor redis

- src/frontend/Komponenter/Behandling/Vurdering/Vurdering.tsx
Favrokort: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24683
Vi ønsker å legge til  teksten:
'
Dokumentasjon og utredning 
Spørsmålet i saken 
Aktuelle rettskilder 
Klagers anførsler 
Vurdering av klagen'
I fritekstfeltet dersom det ikke eksisterer noe der fra før. 
Se video:
Før:
https://github.com/user-attachments/assets/7b4591fe-aca0-40ae-a83e-4459c1e736bd
Etter:
https://github.com/user-attachments/assets/ee68b8db-c360-4bc6-b4e2-3dd87b9029d1
> Legger til standard tekst for instilling hvis det ikke finnes fra før

- package.json
- src/frontend/Komponenter/Behandling/BehandlingContainer.tsx
- src/frontend/Komponenter/Behandling/Brev/PdfVisning.tsx
- src/frontend/Komponenter/Behandling/Formkrav/EndreFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Formkrav/VisFormkravVurderinger.tsx
- src/frontend/Komponenter/Behandling/Resultat/Resultat.tsx
- src/frontend/Komponenter/Behandling/Resultat/Tidslinje.tsx
Fikset en plagsom warning som dukker opp i pre-commit. I samme slengen hiver jeg inn noen scripts for å validere koden.
> Validering og warnings

- src/frontend/Komponenter/Behandling/Brevmottakere/baks/BrevmottakerContainer.tsx
- src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/BrevmottakerDetaljer.tsx
- src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/BrevmottakerModal.tsx
- src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/BrevmottakerModalBody.tsx
- src/frontend/Komponenter/Behandling/Brevmottakere/baks/modal/form/BrevmottakerForm.tsx
- src/frontend/Komponenter/Behandling/Brevmottakere/slettbarBrevmottaker.ts
Favro: [NAV-25011](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25011)
Refaktorer brevmottaker form for å gjøre det mer gjenbrukbart slik at det lettere kan integreres i "henlegg behandling" modalen i en senere PR. 
Har kjørt opp løsningen lokalt og alt ser ut til å fungere fint.
> NAV-25011: Refaktorer brevmottaker form for å gjøre det mer gjenbrukbart slik at det lettere kan integreres i "henlegg behandling" modalen

- .nais/webpack/webpack.dev.js
- .nais/webpack/webpack.prod.js
- eslint.config.mjs
- package.json
- src/frontend/@types/index.d.ts
- src/frontend/Komponenter/Behandling/Resultat/Resultat.module.css
- src/frontend/Komponenter/Behandling/Resultat/Resultat.tsx
- src/frontend/Komponenter/Behandling/Resultat/Tidslinje.tsx
- src/global.d.ts
- tsconfig.frontend.json
- yarn.lock
Starten på utfasing av styled-components biblioteket. Det vedlikeholdes ikke lenger og må byttes ut.
Testet i preprod ✅
> skal kunne bruke css moduler
